name: Run tests

on:
    push:
        branches:
            - 'main'
            - 'auto_tests'
    pull_request:
        branches:
            - 'main'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: 20
            - name: Install dependencies
              run: npm install
              working-directory: ./backend
            - name: Run tests
              run: npm test
              working-directory: ./backend
            - name: Run echo
              run: echo "Hello world"